name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  code-quality:
    uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-ci.yml@v2.5.2
    with:
      enable-coverage: false
      enable-python-wheel: false
